"""empty message

Revision ID: 313f6e6fc47c
Revises: 8ca2425a2f5a
Create Date: 2022-09-27 11:21:01.887669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '313f6e6fc47c'
down_revision = '8ca2425a2f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('horarios', 'dia',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('horarios', 'hora_entrada',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('horarios', 'hora_salida',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.add_column('item_ventas', sa.Column('bon_gan', sa.Float(), nullable=True))
    op.add_column('ventas', sa.Column('total_importe', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'total_importe')
    op.drop_column('item_ventas', 'bon_gan')
    op.alter_column('horarios', 'hora_salida',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('horarios', 'hora_entrada',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('horarios', 'dia',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
