"""empty message

Revision ID: 3c11a86a98ef
Revises: 350067bacc39
Create Date: 2022-08-25 00:38:37.100159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c11a86a98ef'
down_revision = '350067bacc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleados_horarios')
    op.add_column('horarios', sa.Column('empleado_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'horarios', 'empleados', ['empleado_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'horarios', type_='foreignkey')
    op.drop_column('horarios', 'empleado_id')
    op.create_table('empleados_horarios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_empleado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_horario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], name='empleados_horarios_ibfk_1'),
    sa.ForeignKeyConstraint(['id_horario'], ['horarios.id'], name='empleados_horarios_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
