"""empty message

Revision ID: 4664ecac0552
Revises: e3bc80b43cde
Create Date: 2022-09-28 10:45:40.315199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4664ecac0552'
down_revision = 'e3bc80b43cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_presupuestos', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('items_presupuestos', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_presupuestos', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('items_presupuestos', 'id')
    # ### end Alembic commands ###
