"""empty message

Revision ID: 7b138e4ccdad
Revises: 4664ecac0552
Create Date: 2022-09-29 16:25:53.508627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b138e4ccdad'
down_revision = '4664ecac0552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presupuestos', sa.Column('total_importe', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presupuestos', 'total_importe')
    # ### end Alembic commands ###
