"""empty message

Revision ID: 8ca2425a2f5a
Revises: 3c11a86a98ef
Create Date: 2022-08-25 13:36:27.174437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ca2425a2f5a'
down_revision = '3c11a86a98ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horarios', sa.Column('dia', sa.String(length=10), nullable=True))
    op.add_column('horarios', sa.Column('hora_entrada', sa.String(length=5), nullable=True))
    op.add_column('horarios', sa.Column('hora_salida', sa.String(length=5), nullable=True))
    op.create_unique_constraint('_dia_empleado', 'horarios', ['dia', 'empleado_id'])
    op.drop_column('horarios', 'fecha_fin')
    op.drop_column('horarios', 'fecha_inicio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horarios', sa.Column('fecha_inicio', mysql.DATETIME(), nullable=True))
    op.add_column('horarios', sa.Column('fecha_fin', mysql.DATETIME(), nullable=True))
    op.drop_constraint('_dia_empleado', 'horarios', type_='unique')
    op.drop_column('horarios', 'hora_salida')
    op.drop_column('horarios', 'hora_entrada')
    op.drop_column('horarios', 'dia')
    # ### end Alembic commands ###
