"""empty message

Revision ID: adc29a704999
Revises: 313f6e6fc47c
Create Date: 2022-09-28 10:20:21.779160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adc29a704999'
down_revision = '313f6e6fc47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_presupuestos', sa.Column('order_id', sa.Integer(), nullable=False))
    op.alter_column('items_presupuestos', 'presupuesto_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('items_presupuestos', 'descripcion',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items_presupuestos', 'cantidad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('items_presupuestos', 'bon_gan',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('items_presupuestos', 'precio',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('items_presupuestos', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_presupuestos', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.alter_column('items_presupuestos', 'precio',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('items_presupuestos', 'bon_gan',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('items_presupuestos', 'cantidad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('items_presupuestos', 'descripcion',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('items_presupuestos', 'presupuesto_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('items_presupuestos', 'order_id')
    # ### end Alembic commands ###
