"""empty message

Revision ID: bdca0dc80844
Revises: 7b138e4ccdad
Create Date: 2022-09-30 22:05:35.656781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdca0dc80844'
down_revision = '7b138e4ccdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('horarios', 'dia',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10),
               nullable=True)
    op.alter_column('horarios', 'hora_entrada',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=5),
               nullable=True)
    op.alter_column('horarios', 'hora_salida',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=5),
               nullable=True)
    op.alter_column('horarios', 'empleado_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('item_ventas', sa.Column('bon_gan', sa.Float(), nullable=True))
    op.alter_column('items_presupuestos', 'descripcion',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items_presupuestos', 'cantidad',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('items_presupuestos', 'bon_gan',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('items_presupuestos', 'precio',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.add_column('presupuestos', sa.Column('total_importe', sa.Float(), nullable=True))
    op.add_column('ventas', sa.Column('total_importe', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'total_importe')
    op.drop_column('presupuestos', 'total_importe')
    op.alter_column('items_presupuestos', 'precio',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('items_presupuestos', 'bon_gan',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('items_presupuestos', 'cantidad',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('items_presupuestos', 'descripcion',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('item_ventas', 'bon_gan')
    op.alter_column('horarios', 'empleado_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('horarios', 'hora_salida',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=5),
               nullable=False)
    op.alter_column('horarios', 'hora_entrada',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=5),
               nullable=False)
    op.alter_column('horarios', 'dia',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10),
               nullable=False)
    # ### end Alembic commands ###
